server:
    address: 0.0.0.0
    port: 8761

eureka:
  instance:
    hostname: 192.168.48.10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0